# Generated by Django 4.1 on 2022-09-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='caregory',
            new_name='category',
        ),
    ]
