# Generated by Django 4.1 on 2022-09-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
